language: java
sudo: enabled

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y rake
  - chmod +x gradlew

  - export ANDROID_HOME=/usr/local/android-sdk
  - export PATH=$PATH:$ANDROID_HOME

notifications:
  email:
    - cwagthomas@gmail.com
    - kurdtpage@gmail.com
    - miho19@hotmail.co.nz
