sudo: false
language: android

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-26.1.0

    # The SDK version used to compile your project
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-26
    - sys-img-armeabi-v7a-android-17

    # Android SDK components
    - extra

before_install:
 - chmod +x gradlew
 - yes 'y' | sdkmanager --update
 - yes 'y' | sdkmanager --licenses

script:
  - ./gradlew clean test build

notifications:
  email:
    - cwagthomas@gmail.com
    - kurdtpage@gmail.com
    - miho19@hotmail.co.nz

after_success:
  cat /home/travis/build/OwlNavi/345_app/app/build/reports/lint-rsults.html