language: android
sudo: enabled

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y rake
  - chmod +x gradlew

notifications:
  email:
    - cwagthomas@gmail.comx
    - kurdtpage@gmail.com
    - miho19@hotmail.co.nzx
